# This code performs generates Venn diagrams for CTS
# Generated by: Yuxi Sun
# Last update: 04/03/2020

setwd("/Users/jennifersun/Desktop/BioTIP_Applications/input.Rdata/GSE6136")
five <- get(load("CTS.GSE6136_5states_5per.rData"))
one <- get(load("CTS.GSE6136_5states_1per.rData"))
length(intersect(five,one))
# [1] 24

library(VennDiagram)
grid.newpage()
draw.pairwise.venn(area1=35, area2=141, cross.area=24,
                   category = c("1 per","5 per"),
                   col = c("red","red"), lt = c("solid","dashed"))
dev.copy2pdf(file = 'venn_1per_vs_5per.pdf')

almost_true <- get(load("CTS.GSE6136_mislabel_GSM142409.rData")) #120
true <- get(load("CTS.GSE6136_5states_1per.rData")) #35
misclassify <- get(load("CTS.GSE6136_mislabel_GSM142418.rData")) #51
length(intersect(almost_true,misclassify))
# [1] 0
length(intersect(almost_true,true))
# [1] 7
length(intersect(misclassify,true))
# [1] 0

grid.newpage()
draw.triple.venn(area1 = 35,
                 area2 = 120,
                 area3 = 51,
                 n12 = 7,
                 n13 = 0,
                 n23 = 0,
                 n123 = 0,
                 category = c("True","Almost True","Misclassified"),
                 fill = c("red","white","white"),
                 col = c("red","green","khaki3"),
                 cat.col = c("red","green","khaki3"))
dev.copy2pdf(file = 'venn_true_vs_almost_true_vs_misclassified.pdf')
