# This code performs CTS analysis on the log2-transformed gene expressional data of GSE6136, using BioTIP (v.1.1.1).
# Generated by: Zhezhen Wang
# Revised by: Xinan H Yang (xyang2_at_uchicago.edu), Yuxi Sun (ysun11_at_uchicago.edu)
# Last update: 04/03/2020

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')
BiocManager::install("BioTIP")
library(BioTIP)
packageVersion("BioTIP")  #[1] 'v. 1.1.1'

library(stringr)
library(psych)
library(igraph)

####################### load in the downloaded expressinal matrix of GSE6136 #####################
setwd("/Users/jennifersun/Desktop/BioTIP_Applications/input.Rdata/GSE6136")
GSE6136 = read.table("GSE6136_matrix.txt",head = T)
dim(GSE6136) #[1] 22690    27
row.names(GSE6136) = GSE6136$ID_REF
GSE6136 = GSE6136[,-1]
dim(GSE6136) #[1] 22690    26
GSE6136 = as.matrix(GSE6136)

## read the published sample states
cli = read.delim("GSE6136_cli.txt",head = F)
cli = t(cli)
colnames(cli) = str_split_fixed(cli[1,],'_',2)[,2]
cli = cli[-1,]
cli = data.frame(cli)
cli[,'cell-type:ch1'] = str_split_fixed(cli$characteristics_ch1.1,': ',2)[,2]
cli[,'Ig clonality:ch1'] = str_split_fixed(cli$characteristics_ch1.3,': ',2)[,2]


### F:\ZheZhen\NB\DNS\result\mislabel\PCA_vsn_category_wname.pdf 1 sample from lymphoma_marginal to activated
cli[which(cli$geo_accession == 'GSM142409'),'cell-type:ch1'] = 'activated' #almost true
cli$group = cli[,'cell-type:ch1']

## step 1) log transform and adjust to avoide negative inf
df = log2(GSE6136+1)
tmp = names(table(cli$group))
cli$group = factor(cli$group, levels=c('resting','activated','lymphoma_marginal','lymphoma_transitional','lymphoma_aggressive'))
table(cli$group)
#resting             activated     lymphoma_marginal lymphoma_transitional 
#5                     3                     6                     5 
#lymphoma_aggressive 
#7 
samplesL = split(cli$geo_accession,f = cli$group)
subcounts = sd_selection(df,samplesL)

#mislabel = row.names(subcounts[['activate']])
#save(mislabel, file = 'mislabel_preselect_GSM142409.rData')

sapply(subcounts,dim)

igraphL = getNetwork(subcounts,fdr=1)

## step 3.2) Network partition using random walk
## this step constructs modules (geoups of transcriopts) based on their expression levels
cluster = getCluster_methods(igraphL)

## step 4.1-4.3) calculate MCI score for each module
membersL_noweight = getMCI(cluster,subcounts,adjust.size = F)
par(mar=c(1,1,1,1))
plotBar_MCI(membersL_noweight,ylim = c(0,4),min = 30)
dev.copy2pdf(file = 'bar_GSE6136_mislabel_GSM142409.pdf')

maxMCIms <- getMaxMCImember(membersL_noweight[[1]],membersL_noweight[[2]],min =30)

maxMCI = getMaxStats(membersL_noweight[['MCI']],maxMCIms[[1]])
## get biomodule with the highest MCI, CTS
CTS = getCTS(maxMCI, maxMCIms[[2]])
#Length: 120

save(CTS, file = 'CTS.GSE6136_mislabel_GSM142409.rData')


#simMCI = simulationMCI(105,samplesL, df)
#plot_MCI_Simulation(maxMCI,simMCI,ylim =c(0,4),las = 2,order = c('resting','activated','lymphoma_marginal','lymphoma_transitional','lymphoma_aggressive'))

Ic = getIc(df,samplesL,CTS,fun='BioTIP')
simIc = simulation_Ic(length(CTS),samplesL,df,fun='BioTIP')
par(resetPar())
plot_Ic_Simulation(Ic,simIc,ylim = c(0,1),
                   las = 2, ylab = "Ic*",
                   order = c('resting','activated','lymphoma_marginal','lymphoma_transitional','lymphoma_aggressive'),
                   fun='boxplot')

dev.copy2pdf(file = 'MCI_Ic_GSE6136_almost_trues_GSM142409.pdf')

############################### negative control succeed: identifiying 'lymphoma_agressive' as tipping point
cli[which(cli$geo_accession == 'GSM142409'),'cell-type:ch1'] = 'lymphoma_marginal' #revert almost true (GSM142409)
cli[which(cli$geo_accession == 'GSM142418'),'cell-type:ch1'] = 'activated' #misclassify

cli$group = cli[,'cell-type:ch1']
cli$group = factor(cli$group, levels=c('resting','activated','lymphoma_marginal','lymphoma_transitional','lymphoma_aggressive'))
table(cli$group)
#resting             activated     lymphoma_marginal lymphoma_transitional 
#5                     4                     6                     5 
#lymphoma_aggressive 
#6 
samplesL = split(cli$geo_accession,f = cli$group)
subcounts = sd_selection(df,samplesL)

#mislabel = row.names(subcounts[['activate']])
#save(mislabel, file = 'mislabel_preselect_GSM142418.rData')

sapply(subcounts,dim)

igraphL = getNetwork(subcounts,fdr=1)


## step 3.2) Network partition using random walk
## this step constructs modules (geoups of transcriopts) based on their expression levels
cluster = getCluster_methods(igraphL)

## step 4.1-4.3) calculate MCI score for each module
membersL_noweight = getMCI(cluster,subcounts,adjust.size = F)
par(mar=c(1,1,1,1))
plotBar_MCI(membersL_noweight,ylim = c(0,5),min = 30)

maxMCIms <- getMaxMCImember(membersL_noweight[[1]],membersL_noweight[[2]],min =30)

maxMCI = getMaxStats(membersL_noweight[['MCI']],maxMCIms[[1]])
## get biomodule with the highest MCI, CTS
CTS = getCTS(maxMCI, maxMCIms[[2]])
#Length: 51

save(CTS, file = 'CTS.GSE6136_mislabel_GSM142418.rData')

#par(mfrow = c(2,1))
#simMCI = simulationMCI(105,samplesL, df)
#plot_MCI_Simulation(maxMCI,simMCI,ylim =c(0,5),las = 2,order = c('resting','activated','lymphoma_marginal','lymphoma_transitional','lymphoma_aggressive'))

Ic = getIc(df,samplesL,CTS,fun='BioTIP')
simIc = simulation_Ic(length(CTS),samplesL,df,fun='BioTIP')
par(resetPar())
plot_Ic_Simulation(Ic,simIc,ylim = c(0,1.5),
                   las = 2, ylab = "Ic*",
                   order = c('resting','activated','lymphoma_marginal','lymphoma_transitional','lymphoma_aggressive'),
                   fun='boxplot')

dev.copy2pdf(file = 'MCI_Ic_GSE6136_mislabel_GSM142418.pdf')